[tool.poetry]
name = "application"
version = "0.1.0"
description = ""
authors = ["matthew <matthew@cupist.com>"]

[tool.poetry.dependencies]
python = "^2.7"
flask = "^1.1.1"
flasgger = "^0.9.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
