[tool.poetry]
name = "application"
version = "0.1.0"
description = "flask-toy project"
authors = ["matthew <homekeeper89@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^2.7"
flasgger = "^0.9.4"
flask = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
