FROM python:3.8-slim

RUN pip install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock .

RUN cd /tmp && poetry install --no-root

# Copy in everything else:
COPY . .

RUN poetry install

CMD flask run --host=0.0.0.0
