"""please-2

Revision ID: d27c50be590b
Revises: 7fa35b0e4d6f
Create Date: 2020-04-10 09:32:52.698822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d27c50be590b"
down_revision = "7fa35b0e4d6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authentications",
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("category", sa.String(length=10), nullable=False),
        sa.Column("identification", sa.String(20), nullable=True),
        sa.Column("secret", sa.String(20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "category"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("nickname", sa.String(length=50), nullable=True),
        sa.Column("birthday", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("authentications")
    # ### end Alembic commands ###
