version: "3"

services:
  flask_web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
      args:
        runfile: app.py
  my_redis:
    image: redis:4.0.11-alpine
  my_sql:
    image: mysql:5.6
