version: "3"

services:
  flask_web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
      args:
        runfile: app.py
    ports:
      - 5000:5000

  my_redis:
    image: redis:4.0.11-alpine
    container_name: redis_container

  my_sql:
    image: mysql:5.6
    container_name: sql_container
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=homekeeper
      - MYSQL_PASSWORD=dev
