version: "3"

services:
  my_docker_app:
    build:
      context: ./docker
      dockerfile: Dockerfile-dev
      args:
        buildno: 1
        gitcommithash: cdc3b19
    volumes:
      - "./my_secret:/src"
