version: "3"

services:
  flask_web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-ver
      args:
        runfile: app.py
    ports:
      - 5000:5000

  my_redis:
    image: redis:4.0.11-alpine
    container_name: redis_container
    ports:
      - 6379:6379

  my_sql:
    image: mysql:5.7
    restart: always
    container_name: mysql_5.7_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=dev
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 5678:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
